#!/usr/bin/env python3
"""
处理 XTB 优化输出的 SDF 文件
- 提取第一行中的能量信息，保存为 Energy_xTB tag（纯数值）
- 设置正确的 Title（通过命令行参数或从原文件推断）
- 清理第一行的多余信息
"""

import re
import sys
import argparse
from pathlib import Path
from typing import Optional, Tuple


def parse_xtb_sdf_header(first_line: str) -> Optional[float]:
    """
    解析 XTB SDF 文件的第一行，提取能量值
    
    格式示例: " energy: -43.838958524234 gnorm: 0.000108904450 xtb: 6.7.1 (a57fabb)"
    
    Returns:
        energy: 能量值（Hartree），如果未找到则返回 None
    """
    energy_match = re.search(r'energy:\s+([-\d.]+)', first_line)
    if energy_match:
        return float(energy_match.group(1))
    return None


def process_xtb_sdf(input_file: str, output_file: str, title: Optional[str] = None):
    """
    处理 XTB 输出的 SDF 文件
    
    Parameters
    ----------
    input_file : str
        输入的 XTB SDF 文件（通常是 xtbopt.sdf）
    output_file : str
        输出的 SDF 文件
    title : str, optional
        要设置的 Title，如果不提供则自动生成
    """
    with open(input_file, 'r') as f:
        lines = f.readlines()
    
    if len(lines) < 1:
        print(f"错误: {input_file} 文件为空")
        return False
    
    # 解析第一行，提取能量
    first_line = lines[0].strip()
    energy = parse_xtb_sdf_header(first_line)
    
    # 确定 Title
    if title is None:
        # 从原文件名生成 Title
        input_path = Path(input_file)
        title = input_path.stem.replace('_opt', '').replace('.sdf', '')
        if not title:
            title = "XTB_Optimized"
    
    # 构建新的文件内容
    new_lines = []
    
    # 第一行：Title（原来的第一行被替换）
    new_lines.append(title + '\n')
    
    # 第二行：程序信息行（保持不变）
    if len(lines) > 1:
        new_lines.append(lines[1])
    else:
        new_lines.append("  Generated by XTB\n")
    
    # 第三行及以后：保留原始内容，但跳过第一行
    for i in range(2, len(lines)):
        new_lines.append(lines[i])
    
    # 在原子块之前添加 Energy_xTB tag（纯数值，不带注释）
    # 找到 M END 行之前的位置来插入 tag
    insert_pos = -1
    for i, line in enumerate(new_lines):
        if line.strip() == 'M  END':
            insert_pos = i
            break
    
    if insert_pos != -1 and energy is not None:
        # 在 M END 之前插入能量 tag（纯数值格式）
        # SDF tag 格式: > <TagName>
        #              数值
        #              （空行）
        energy_tag = f"> <Energy_xTB>\n{energy:.10f}\n\n"
        new_lines.insert(insert_pos, energy_tag)
    
    # 写入输出文件
    with open(output_file, 'w') as f:
        f.writelines(new_lines)
    
    # 打印信息
    print(f"处理完成:")
    print(f"  输入文件: {input_file}")
    print(f"  输出文件: {output_file}")
    print(f"  Title: {title}")
    if energy is not None:
        print(f"  Energy_xTB: {energy:.10f} Hartree ({energy * 627.509474:.2f} kcal/mol)")
    else:
        print(f"  警告: 未找到能量信息")
    
    return True


def batch_process(input_dir: str, output_dir: str, suffix: str = "_processed.sdf"):
    """
    批量处理目录中的所有 XTB SDF 文件
    
    Parameters
    ----------
    input_dir : str
        输入目录
    output_dir : str
        输出目录
    suffix : str
        输出文件后缀
    """
    input_path = Path(input_dir)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    for sdf_file in input_path.glob("*.sdf"):
        if sdf_file.name.startswith("xtbopt"):
            output_file = output_path / f"{sdf_file.stem}{suffix}.sdf"
            process_xtb_sdf(str(sdf_file), str(output_file))
        else:
            # 处理其他可能的 XTB 输出文件
            output_file = output_path / f"{sdf_file.stem}_processed.sdf"
            process_xtb_sdf(str(sdf_file), str(output_file))


def main():
    parser = argparse.ArgumentParser(
        description='处理 XTB 优化的 SDF 文件，提取能量信息为 SDF tag',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  %(prog)s xtbopt.sdf -o xtbopt_fixed.sdf
  %(prog)s xtbopt.sdf -t "My Molecule" -o output.sdf
  %(prog)s --batch ./results/ -o ./processed/ -s "_xtb"
        """
    )
    
    parser.add_argument('input', help='输入 SDF 文件（或使用 --batch 时指定目录）')
    parser.add_argument('-o', '--output', help='输出 SDF 文件')
    parser.add_argument('-t', '--title', help='SDF 文件的 Title（第一行）')
    parser.add_argument('--batch', action='store_true', 
                        help='批量处理模式，此时 input 参数应为目录')
    parser.add_argument('--output-dir', default='./processed',
                        help='批量处理时的输出目录（默认: ./processed）')
    parser.add_argument('--suffix', default='_processed',
                        help='批量处理时的输出文件后缀（默认: _processed）')
    
    args = parser.parse_args()
    
    if args.batch:
        batch_process(args.input, args.output_dir, args.suffix)
    else:
        if not args.output:
            # 自动生成输出文件名
            input_path = Path(args.input)
            args.output = input_path.parent / f"{input_path.stem}_processed.sdf"
        
        process_xtb_sdf(args.input, args.output, args.title)


if __name__ == "__main__":
    main()
